# Generated by Django 4.0.5 on 2022-09-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=35)),
                ('subtitle', models.CharField(max_length=100)),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.TextField()),
                ('text_color', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('White', 'White'), ('Purple', 'Purple'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Black', 'Black'), ('Orange', 'Orange'), ('Grey', 'Grey')], max_length=15)),
                ('background_color', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('White', 'White'), ('Purple', 'Purple'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Black', 'Black'), ('Orange', 'Orange'), ('Grey', 'Grey')], max_length=15)),
                ('url', models.TextField(null=True)),
                ('index', models.IntegerField()),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=35, null=True)),
                ('title_color', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('White', 'White'), ('Purple', 'Purple'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Black', 'Black'), ('Orange', 'Orange'), ('Grey', 'Grey')], max_length=15)),
                ('subtitle', models.CharField(blank=True, max_length=35, null=True)),
                ('subtitle_color', models.CharField(choices=[('Green', 'Green'), ('Red', 'Red'), ('White', 'White'), ('Purple', 'Purple'), ('Yellow', 'Yellow'), ('Pink', 'Pink'), ('Black', 'Black'), ('Orange', 'Orange'), ('Grey', 'Grey')], max_length=15)),
                ('url', models.TextField(null=True)),
                ('index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('link', models.TextField()),
                ('products', models.ManyToManyField(blank=True, to='blog.producttype')),
            ],
        ),
    ]
