# Generated by Django 4.0.5 on 2022-09-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_datatonewsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=318, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DataToNewsletter',
        ),
    ]
