# Generated by Django 4.0.5 on 2022-09-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newsletteremail_delete_datatonewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletteremail',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
