# Generated by Django 4.1.1 on 2022-10-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_account_last_seen_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_seen_products',
            field=models.ManyToManyField(blank=True, default=None, related_name='last_seen_products', to='blog.product'),
        ),
        migrations.AlterField(
            model_name='account',
            name='products_in_cart',
            field=models.ManyToManyField(blank=True, default=None, to='blog.product'),
        ),
    ]
