# Generated by Django 4.1.1 on 2022-09-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='category',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
