# Generated by Django 4.1.1 on 2022-09-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options_category_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('price', models.FloatField()),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('has_small', models.BooleanField()),
                ('has_medium', models.BooleanField()),
                ('has_large', models.BooleanField()),
                ('gender', models.CharField(choices=[('W', 'Woman'), ('M', 'Men'), ('U', 'Unissex')], max_length=1)),
                ('composition', models.TextField()),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.producttype')),
            ],
        ),
    ]
